<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SIDCD558" name="com.xp8.test.XP8_Sanity_Test_BEL" tests="34" failures="2" timestamp="12 Mar 2018 04:38:33 GMT" time="2747.006" errors="5">
  <testcase name="XP8_Sanity_018_VerifyUserCan_Delete_DesiredContact_SIMcard" time="78.284" classname="com.xp8.test.XP8_Sanity_Test_BEL">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.xp8.util.XP8_Sanity_Util_BEL.validate_ContactDelete(XP8_Sanity_Util_BEL.java:914)
	at com.xp8.test.XP8_Sanity_Test_BEL.XP8_Sanity_018_VerifyUserCan_Delete_DesiredContact_SIMcard(XP8_Sanity_Test_BEL.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- XP8_Sanity_018_VerifyUserCan_Delete_DesiredContact_SIMcard -->
  <testcase name="XP8_Sanity_013_Verify_Able_Initiate_MO_Calls_From_CallLog" time="79.838" classname="com.xp8.test.XP8_Sanity_Test_BEL">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.xp8.util.XP8_Sanity_Util_BEL.validate_Num_In_CallLog(XP8_Sanity_Util_BEL.java:705)
	at com.xp8.test.XP8_Sanity_Test_BEL.XP8_Sanity_013_Verify_Able_Initiate_MO_Calls_From_CallLog(XP8_Sanity_Test_BEL.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- XP8_Sanity_013_Verify_Able_Initiate_MO_Calls_From_CallLog -->
  <testcase name="XP8_Sanity_005_Verify_ON_And_OFF_WiFi_Quick_Panel" time="68.591" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_023_Verify_Able_Perform_MultiRadioAccessBearer" time="117.809" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_034_Verify_SIM_PIN_Lock_Enabled_From_Settings" time="138.555" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_035_Verify_Sending_Receive_SMS_While_Camped_To_LTE_Network" time="109.995" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_015_Verify_Able_Add_NewContact_SIMcard" time="85.472" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_008_Verify_ON_And_OFF_AirplaneMode_Quick_Panel" time="85.005" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_027_Verify_APN_Correctness_Before_after_RestoringDefault_APNs" time="42.640" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_019_Verify_UserCan_Send_SinglePage_SMS" time="277.391" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_030_Verify_Able_to_Launch_And_Check_CalculatorApp" time="93.597" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_007_Verify_ON_And_OFF_DataService_Quick_Panel" time="58.708" classname="com.xp8.test.XP8_Sanity_Test_BEL">
    <failure type="org.openqa.selenium.NoSuchElementException" message="Can&#039;t locate an element by this strategy: Locator map: 
- native content: &quot;By.xpath: //android.widget.EditText[@resource-id=&#039;com.android.chrome:id/url_bar&#039;]&quot; 
- html content: &quot;by id or name &quot;urlBar_Chrome&quot;&quot;
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;2.53.0&#039;, revision: &#039;35ae25b1534ae328c771e0856c93e187490ca824&#039;, time: &#039;2016-03-15 10:43:46&#039;
System info: host: &#039;SIDCD558&#039;, ip: &#039;10.15.3.8&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_144&#039;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: 
- native content: "By.xpath: //android.widget.EditText[@resource-id='com.android.chrome:id/url_bar']" 
- html content: "by id or name "urlBar_Chrome""
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'SIDCD558', ip: '10.15.3.8', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_144'
Driver info: driver.version: unknown
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:152)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:51)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$196ad464.isDisplayed(<generated>)
	at com.xp8.util.BaseUtil.enterTextToInputField(BaseUtil.java:218)
	at com.xp8.util.XP8_Sanity_Util_BEL.validate_And_BrowseIn_Chrome(XP8_Sanity_Util_BEL.java:1112)
	at com.xp8.test.XP8_Sanity_Test_BEL.XP8_Sanity_007_Verify_ON_And_OFF_DataService_Quick_Panel(XP8_Sanity_Test_BEL.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- XP8_Sanity_007_Verify_ON_And_OFF_DataService_Quick_Panel -->
  <testcase name="XP8_Sanity_024_Verify_UserAble_Search_URLbar_from_Browser" time="172.964" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_012_Verify_the_CallLogs" time="62.917" classname="com.xp8.test.XP8_Sanity_Test_BEL">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.xp8.util.XP8_Sanity_Util_BEL.validate_Num_In_CallLog(XP8_Sanity_Util_BEL.java:705)
	at com.xp8.test.XP8_Sanity_Test_BEL.XP8_Sanity_012_Verify_the_CallLogs(XP8_Sanity_Test_BEL.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- XP8_Sanity_012_Verify_the_CallLogs -->
  <testcase name="XP8_Sanity_032_Verify_User_Able_Lauch_Clock_Menus" time="57.185" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_002_Verify_ChargingStatusOfBatteryIcon" time="27.702" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_031_Verify_Launch_Sound_Recorder_And_Check_Recording" time="74.268" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_003_Verify_EnableAndDisable_FlightMode" time="96.012" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_036_Verify_USB_Power_Saving_Option_Present_SystemSettings" time="26.674" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_017_Verify_UserCan_Delete_DesiredContact" time="83.653" classname="com.xp8.test.XP8_Sanity_Test_BEL">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.xp8.util.XP8_Sanity_Util_BEL.validate_ContactDelete(XP8_Sanity_Util_BEL.java:914)
	at com.xp8.test.XP8_Sanity_Test_BEL.XP8_Sanity_017_Verify_UserCan_Delete_DesiredContact(XP8_Sanity_Test_BEL.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- XP8_Sanity_017_Verify_UserCan_Delete_DesiredContact -->
  <testcase name="XP8_Sanity_022_Verify_AbleTo_SendSMS_OnActiveVoiceCall" time="126.924" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_028_Verify_Able_Switch_ON_OFF_Flashlight_Quickpanel" time="33.466" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_006_Verify_ON_And_OFF_Bluetooth_Quick_Panel" time="55.640" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_029_Verify_Able_Launch_Chrome_Browse_URL" time="88.158" classname="com.xp8.test.XP8_Sanity_Test_BEL">
    <failure type="org.openqa.selenium.NoSuchElementException" message="Can&#039;t locate an element by this strategy: Locator map: 
- native content: &quot;By.xpath: //android.widget.Image[@text=&#039;Sign in&#039;]&quot; 
- html content: &quot;by id or name &quot;bbc_logo_2&quot;&quot;
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;2.53.0&#039;, revision: &#039;35ae25b1534ae328c771e0856c93e187490ca824&#039;, time: &#039;2016-03-15 10:43:46&#039;
System info: host: &#039;SIDCD558&#039;, ip: &#039;10.15.3.8&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_144&#039;
Driver info: driver.version: unknown">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: 
- native content: "By.xpath: //android.widget.Image[@text='Sign in']" 
- html content: "by id or name "bbc_logo_2""
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'SIDCD558', ip: '10.15.3.8', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_144'
Driver info: driver.version: unknown
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:152)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:51)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$196ad464.isDisplayed(<generated>)
	at com.xp8.util.XP8_Sanity_Util_BEL.validate_And_BrowseIn_Chrome(XP8_Sanity_Util_BEL.java:1126)
	at com.xp8.test.XP8_Sanity_Test_BEL.XP8_Sanity_029_Verify_Able_Launch_Chrome_Browse_URL(XP8_Sanity_Test_BEL.java:549)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- XP8_Sanity_029_Verify_Able_Launch_Chrome_Browse_URL -->
  <testcase name="XP8_Sanity_001_Verify_Date_TimeAndTimeZone" time="31.066" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_026_Verify_Operator_Homepage_in_NativeBrowser" time="28.583" classname="com.xp8.test.XP8_Sanity_Test_BEL">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.xp8.test.XP8_Sanity_Test_BEL.XP8_Sanity_026_Verify_Operator_Homepage_in_NativeBrowser(XP8_Sanity_Test_BEL.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- XP8_Sanity_026_Verify_Operator_Homepage_in_NativeBrowser -->
  <testcase name="XP8_Sanity_004_Verify_OperatorName_LockScreenAndHomeScreen" time="53.089" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_020_Verify_AbleTo_Enable_Disable_Data_Service" time="124.323" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_011_Verify_Launch_SettingsFromQuickPanel" time="28.880" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_016_Verify_User_CanMake_Call_AnyContact" time="65.953" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_010_Verify_ON_And_OFF_AutoRotate_Quick_Panel" time="46.863" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_025_Verify_OperatorSpecified_PhoneLanguages_in_DUT" time="63.462" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_033_Verify_Internal_Storage_Space_Capacity" time="31.156" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
  <testcase name="XP8_Sanity_014_Verify_Able_To_Add_NewContact" time="132.183" classname="com.xp8.test.XP8_Sanity_Test_BEL"/>
</testsuite> <!-- com.xp8.test.XP8_Sanity_Test_BEL -->
